language: php
sudo: false
php:
- '7.1'
- '7.2'
- '7.3'
cache:
  directories:
  - vendor
before_install:
- composer require php-coveralls/php-coveralls
install:
- composer install --no-interaction
script:
- php ./vendor/bin/phpunit --coverage-clover coverage.xml
after_success:
- travis_retry php ./vendor/bin/php-coveralls -v
notifications:
  email: false
